Fix #856: red vault data shown in blue vault fields
This OUGHT to fix the bug but the Breakdown tab says
“No match breakdown found”. Maybe that has to do with the EventBus
messages:

```
03-16 00:22:20.385
6001-6001/com.thebluealliance.androidclient.development
D/android.view.View: Match key clicked: 2018azfl_qm4
03-16 00:22:20.386
6001-6001/com.thebluealliance.androidclient.development
D/com.thebluealliance.androidclient.helpers.AnalyticsHelper: Loaded
analytics id:
03-16 00:22:20.388
6001-6001/com.thebluealliance.androidclient.development W/GAv4:
Discarding hit. Missing tracking id parameter:
a=1945156119,sf=100.0,t=event,av=4.3.0+dirty,el=,ea=2018azfl_qm4,an=The
Blue Alliance Debug,aid=4.3.0+dirty,tid=,ec=match_click
03-16 00:22:20.397
6001-6425/com.thebluealliance.androidclient.development V/FA: Activity
paused, time: 1396834
03-16 00:22:20.403
6001-6001/com.thebluealliance.androidclient.development V/FA:
onActivityCreated
03-16 00:22:20.411
6001-6001/com.thebluealliance.androidclient.development
I/AppCompatViewInflater: app:theme is now deprecated. Please move to
using android:theme instead.
03-16 00:22:20.414
6001-6001/com.thebluealliance.androidclient.development
I/AppCompatViewInflater: app:theme is now deprecated. Please move to
using android:theme instead.
03-16 00:22:20.421
6001-6001/com.thebluealliance.androidclient.development W/GAv4:
Discarding hit. Missing tracking id parameter:
cd=com.thebluealliance.androidclient.activities.ViewMatchActivity,a=1046
334888,sf=100.0,t=screenview,av=4.3.0+dirty,an=The Blue Alliance
Debug,aid=4.3.0+dirty,tid=
03-16 00:22:20.421
6001-6001/com.thebluealliance.androidclient.development W/GAv4:
Discarding hit. Missing tracking id parameter:
cd=com.thebluealliance.androidclient.activities.ViewMatchActivity,a=1009
986620,sf=100.0,t=screenview,av=4.3.0+dirty,an=The Blue Alliance
Debug,aid=4.3.0+dirty,tid=
03-16 00:22:20.421
6001-6001/com.thebluealliance.androidclient.development W/GAv4:
Discarding hit. Missing tracking id parameter:
cd=com.thebluealliance.androidclient.activities.ViewMatchActivity,a=1851
005739,sf=100.0,t=screenview,av=4.3.0+dirty,an=The Blue Alliance
Debug,aid=4.3.0+dirty,tid=
03-16 00:22:20.421
6001-6001/com.thebluealliance.androidclient.development W/GAv4:
Discarding hit. Missing tracking id parameter:
cd=com.thebluealliance.androidclient.activities.ViewMatchActivity,a=9780
25660,sf=100.0,t=screenview,av=4.3.0+dirty,an=The Blue Alliance
Debug,aid=4.3.0+dirty,tid=
03-16 00:22:20.421
6001-6001/com.thebluealliance.androidclient.development W/GAv4:
Discarding hit. Missing tracking id parameter:
cd=com.thebluealliance.androidclient.activities.ViewMatchActivity,a=1945
156119,sf=100.0,t=screenview,av=4.3.0+dirty,an=The Blue Alliance
Debug,aid=4.3.0+dirty,tid=
03-16 00:22:20.424
6001-6425/com.thebluealliance.androidclient.development V/FA: Activity
resumed, time: 1396861
03-16 00:22:20.432
6001-6001/com.thebluealliance.androidclient.development
D/com.thebluealliance.androidclient.datafeed.DatafeedModule_ProvideTBARe
trofitFactory: Using TBA Host: https://www.thebluealliance.com/
03-16 00:22:20.439
6001-6410/com.thebluealliance.androidclient.development
D/okhttp3.internal.http.RealInterceptorChain: FETCHING
https://www.thebluealliance.com/api/v3/match/2018azfl_qm4
03-16 00:22:20.440
6001-6097/com.thebluealliance.androidclient.development
I/com.thebluealliance.androidclient.subscribers.BaseAPISubscriber:
Showing 2018 breakdowns? false
03-16 00:22:20.440
6001-6097/com.thebluealliance.androidclient.development W/GAv4:
Discarding hit. Missing tracking id parameter:
cd=com.thebluealliance.androidclient.activities.ViewMatchActivity,a=1945
156119,sf=100.0,utt=1183,t=timing,av=4.3.0+dirty,utc=load_timing,utv=Mat
chBreakdownSubscriber,utl=matchBreakdown_2018azfl_qm4,an=The Blue
Alliance Debug,aid=4.3.0+dirty,tid=
03-16 00:22:20.498
6001-6001/com.thebluealliance.androidclient.development W/View:
requestLayout() improperly called by android.widget.ListView{3a1c077
VFED.VC.. ......ID 0,590-1050,2392 #7f0f0105 app:id/left_drawer} during
layout: running second layout pass
03-16 00:22:20.502
6001-6001/com.thebluealliance.androidclient.development
D/com.thebluealliance.androidclient.background.mytba.CreateSubscriptionP
anel: getting notifications for: MATCH
03-16 00:22:20.508
6001-6046/com.thebluealliance.androidclient.development
D/EGL_emulation: eglMakeCurrent: 0xa8a05600: ver 3 0 (tinfo 0xa8a03570)
03-16 00:22:20.524
6001-6046/com.thebluealliance.androidclient.development I/chatty:
uid=10087(u0_a87) RenderThread identical 2 lines
03-16 00:22:20.530
6001-6046/com.thebluealliance.androidclient.development
D/EGL_emulation: eglMakeCurrent: 0xa8a05600: ver 3 0 (tinfo 0xa8a03570)
03-16 00:22:20.534
6001-6046/com.thebluealliance.androidclient.development
D/EGL_emulation: eglMakeCurrent: 0xa8a05600: ver 3 0 (tinfo 0xa8a03570)
03-16 00:22:20.589
6001-6046/com.thebluealliance.androidclient.development I/chatty:
uid=10087(u0_a87) RenderThread identical 3 lines
03-16 00:22:20.594
6001-6046/com.thebluealliance.androidclient.development
D/EGL_emulation: eglMakeCurrent: 0xa8a05600: ver 3 0 (tinfo 0xa8a03570)
03-16 00:22:20.595
6001-6046/com.thebluealliance.androidclient.development
D/OpenGLRenderer: endAllActiveAnimators on 0x92f53680 (RippleDrawable)
with handle 0x94730020
03-16 00:22:20.600
6001-6046/com.thebluealliance.androidclient.development
D/EGL_emulation: eglMakeCurrent: 0xa8a05600: ver 3 0 (tinfo 0xa8a03570)
03-16 00:22:21.003
6001-6105/com.thebluealliance.androidclient.development D/EventBus: No
subscribers registered for event class
com.thebluealliance.androidclient.subscribers.MatchInfoSubscriber$Model
03-16 00:22:21.003
6001-6105/com.thebluealliance.androidclient.development D/EventBus: No
subscribers registered for event class
org.greenrobot.eventbus.NoSubscriberEvent
03-16 00:22:21.003
6001-6410/com.thebluealliance.androidclient.development
D/okhttp3.internal.http.RealInterceptorChain: FETCHING
https://www.thebluealliance.com/api/v3/event/2018azfl
03-16 00:22:21.005
6001-6001/com.thebluealliance.androidclient.development
D/com.thebluealliance.androidclient.subscribers.BaseAPISubscriber:
BINDING DATA
03-16 00:22:21.005
6001-6001/com.thebluealliance.androidclient.development
D/com.thebluealliance.androidclient.subscribers.BaseAPISubscriber:
BINDING COMPLETE; ELAPSED TIME: 0ms
03-16 00:22:21.325
6001-6105/com.thebluealliance.androidclient.development D/EventBus: No
subscribers registered for event class
com.thebluealliance.androidclient.subscribers.MatchInfoSubscriber$Model
03-16 00:22:21.325
6001-6105/com.thebluealliance.androidclient.development D/EventBus: No
subscribers registered for event class
org.greenrobot.eventbus.NoSubscriberEvent
03-16 00:22:21.326
6001-6105/com.thebluealliance.androidclient.development W/GAv4:
Discarding hit. Missing tracking id parameter:
cd=com.thebluealliance.androidclient.activities.ViewMatchActivity,a=1945
156119,sf=100.0,utt=888857,t=timing,av=4.3.0+dirty,utc=load_timing,utv=M
atchInfoSubscriber,utl=matchInfo_2018azfl_qm4,an=The Blue Alliance
Debug,aid=4.3.0+dirty,tid=
03-16 00:22:21.326
6001-6001/com.thebluealliance.androidclient.development
D/com.thebluealliance.androidclient.subscribers.BaseAPISubscriber:
BINDING DATA
03-16 00:22:21.326
6001-6001/com.thebluealliance.androidclient.development
D/com.thebluealliance.androidclient.subscribers.BaseAPISubscriber:
BINDING COMPLETE; ELAPSED TIME: 0ms
```

How to run the tests? Trying to run MatchBreakdownView2018Test as
an Android Instrumented Test failed before I changed any code:

```
java.lang.AssertionError: expected:<1> but was:<0>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.junit.Assert.assertEquals(Assert.java:631)
at
com.thebluealliance.androidclient.views.breakdowns.MatchBreakdownView201
8Test.getView(MatchBreakdownView2018Test.java:55)
at
com.thebluealliance.androidclient.views.breakdowns.MatchBreakdownView201
8Test.testRenderQualMatch(MatchBreakdownView2018Test.java:39)
at java.lang.reflect.Method.invoke(Native Method)
at
org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMet
hod.java:50)
at
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallab
le.java:12)
at
org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMetho
d.java:47)
at
org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod
.java:17)
at
org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.jav
a:26)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner
.java:78)
at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner
.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at
android.support.test.internal.runner.TestExecutor.execute(TestExecutor.j
ava:59)
at
android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunne
r.java:262)
at
android.app.Instrumentation$InstrumentationThread.run(Instrumentation.ja
va:2074)
```

… and testRenderQualMatch() looks like it just records a snapshot.
Does that do a regression test against a previous snapshot?
There’s nothing obvious in there to check values.