fix some of the test errors
This fixes some of the problems.

There are lots of errors `java.util.ServiceConfigurationError:
org.robolectric.internal.ShadowProvider: Provider
org.robolectric.shadows.support.v4.Shadows not a subtype`
which at least in part seems to be due to using a very old version of
Robolectric. Newer versions are compatible with later Android builds,
but they also have API changes. This particular error is supposedly
fixed in release 3.2, but trying to use that got a more basic error (let
alone upgrading to 3.8) that kept any tests from running:

```
DefaultTestRunner.java:26: error: constructor Implementation in class
Implementation cannot be applied to given types;
        return new Config.Implementation(
               ^
  required:
int[],int,int,String,String,String,String,String,String,String,Class<?>[
],String[],Class<? extends Application>,String[],Class<?>
  found:
int[],String,String,String,String,String,String,String,Class<?>[],String
[],Class<TestTbaAndroid>,String[],Class<CAP#1>
  reason: actual and formal argument lists differ in length
  where CAP#1 is a fresh type-variable:
    CAP#1 extends Object from capture of ?
```

Some of the gradle warnings come from

    apply plugin: 'com.facebook.testing.screenshot'

```
WARNING: Configuration 'androidTestCompile' is obsolete and has been
replaced with 'androidTestImplementation'.
It will be removed at the end of 2018
WARNING: Configuration 'androidTestApi' is obsolete and has been
replaced with 'androidTestImplementation'.
It will be removed at the end of 2018
The Task.leftShift(Closure) method has been deprecated and is scheduled
to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at
build_f0nrmj106vzvtku1xoje7yb5h.run(/Users/jerry/dev/the-blue-alliance-a
ndroid/android/build.gradle:4)
        (Run with --stacktrace to get the full stack trace of this
deprecation warning.)
The ConfigurableReport.setDestination(Object) method has been
deprecated and is scheduled to be removed in Gradle 5.0. Please use the
method ConfigurableReport.setDestination(File) instead.
        at
code_coverage_4nvpfevghf39cb3c8tfyfobgg$_run_closure3$_closure4.doCall(/
Users/jerry/dev/the-blue-alliance-android/code_coverage.gradle:23)
        (Run with --stacktrace to get the full stack trace of this
deprecation warning.)
Version: 4.3.0-4+g26b71fb.dirty/4030000
WARNING: Configuration 'compile' is obsolete and has been replaced with
'implementation'.
It will be removed at the end of 2018
registerResGeneratingTask is deprecated, use
registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use
registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use
registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use
registerGeneratedResFolders(FileCollection)

The TaskInternal.execute() method has been deprecated and is scheduled
to be removed in Gradle 5.0. There are better ways to re-use task
logic, see
https://docs.gradle.org/4.4/userguide/custom_tasks.html#sec:reusing_task
_logic.
        at
build_workaround_missing_resou_f524m2091rtt3ispqncm4ndf4$_run_closure1$_
closure2.doCall(/Users/jerry/dev/the-blue-alliance-android/android/build
.workaround-missing-resource.gradle:32)
```